### ISSUE TITLE
software links are broken

### ISSUE THREAD

**Issue by char4816** [radoslav180/DiNGO#1]
Hello,

Thank you for making your software documentation clear and easy to understand. It seems that when I try to use the software "out of the box" that there are broken download links?

For example when I try to run your example file using:

`java -jar Dingo.jar -i cosmic_list.txt -o results -e HPO -ns O`

I get the following error:

```
http://compbio.charite.de/jenkins/job/hpo.annotations.monthly/lastSuccessfulBuild/artifact/annotation/ALL_SOURCES_ALL_FREQUENCIES_genes_to_phenotype.txt
File ./download/hp_annotation_W.txt can't be moved to ./annotations/

term not in ontology: 1
[...]
term not in ontology: 1

./annotations/hp_annotation_W.txt (No such file or directory)
Reading done!
None of the labels in your annotation match with the chosen ontology, please check their compatibility.
```

Does this seem like a fixable problem?  I'm not sure how to find the correct download links for the software.

Thanks in advance,
Chris

**Comment by radoslav180** [comment]
Hi Chris,
It is link related problem. You should use the following link: http://compbio.charite.de/jenkins/job/hpo.annotations/lastSuccessfulBuild/artifact/util/annotation/genes_to_phenotype.txt. The link is contained in the conf.properties file.
Hope this helps!
Best regards,
Radoslav.

**Comment by radoslav180** [comment]
I checked HPO download links and found that the links had changed.  I have updated conf.properties file.
Best regards, 
Radoslav.

**Comment by char4816** [comment]
Thanks Radoslav,

The new links seemed to work, but now I am running into the following error:

```
==> java -jar Dingo.jar -o results -i cosmic_list.txt -ns BP -s Homo_sapiens
None of the labels in your annotation match with the chosen ontology, please check their compatibility.
Ontology:                     GO
Statistical test:             Hypergeometric test
Correction:                   Benjamini & Hochberg False Discovery Rate (FDR) correction
Significance:                 0.05
Namespace:                    biological_process
Representation:               Overrepresentation
Reference set:                Use whole annotation as reference set
Species:                      Homo_sapiens
Discarded evidence code:      []

Cluster name: results
Exception in thread "main" java.lang.NullPointerException
	at bingo.BingoRunner.getSelectedCanonicalNamesFromTextArea(BingoRunner.java:221)
	at bingo.BingoRunner.actionPerformed(BingoRunner.java:174)
	at dingo.Dingo.main(Dingo.java:229)
```
	
Chris

**Comment by radoslav180** [comment]
Hi Chris,
I have found source of the error. Gene Ontology updated GAF file to 2.2 version. This version is very similar to the previous version except Column 4 (“Qualifier”) is now required. I am going to update DiNGO code and upload new jar file very soon.
Best regards,
Radoslav.

**Comment by radoslav180** [comment]
Hi Chris,
The bug has been fixed. Try now, please.

Best regards,
Radoslav.

**Comment by char4816** [comment]
Radoslav,

Everything seems to be working now. Thank you for your support.

Chris
