### ISSUE TITLE
How to format file for the -rs option

### ISSUE THREAD

**Issue by char4816** [radoslav180/DiNGO#2]
Hello Radoslav,

I am wondering how to format the reference set that is used when running DiNGO with the -rs option.

Currently, I am doing `-rs my_file.txt`

where `my_file.txt` contains 11,026 rows (gene names) and looks something like:
```
SCYL3
C1orf112
CFH
FUCA2
GCLC
NFYA
STPG1
...
```

DiNGO seems to be running but isn't returning any results.  This is making me want to double-check the -rs format because I was getting many results when using the default (and not specifying `-rs`):

```
Reference set:                Use whole annotation as reference set
```

Thanks,
Chris

**Comment by radoslav180** [comment]
Hi Chris,
There is nothing special about format of the reference set. You did formatting well. Could you send me file with your reference set to try it out? 

Best regards,
Radoslav

**Comment by char4816** [comment]
Hi Radoslav,

Thank you for your help.  I think you are right, the formatting seems to be okay, and there is just no enrichment in my gene-list when using the background set of genes.
[background_genes.txt](https://github.com/radoslav180/DiNGO/files/8812512/background_genes.txt)

Here is the background file.

Best,
Chris

**Comment by radoslav180** [comment]
Hi Chris,
I have tried out using your gene set as reference set. It is working as expected. 
I called DiNGO as follows:
`-o results2 -i cosmic_list.txt -ns BP -s Homo_sapiens -rs background_genes.txt`

[cosmic_list.txt](https://github.com/radoslav180/DiNGO/files/8812664/cosmic_list.txt)

[results2.txt](https://github.com/radoslav180/DiNGO/files/8812655/results2.txt)

**Comment by char4816** [comment]
Fantastic.  Thank you for your help.
